# -*- coding: utf-8 -*-
"""01_Grad_descent_linear_reg_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcABiuhnf5fcCs64v_ph0zLqtf9Fa5YW

## ML Review and Gradient Descent Example

In this notebook, we will solve a simple linear regression problem by gradient descent.
"""

import numpy as np
import matplotlib.pyplot as plt

"""## Generate Data from a known distribution
Below we will generate data a known distribution.  
Specifically, the true model is:

$Y = b + \theta_1 X_1 + \theta_2 X_2 + \epsilon$

$X_1$ and $X_2$ have a uniform distribution on the interval $[0,10]$.

We set actual values for $b$ ,$\theta_1$, and $\theta_2$

Here $b=1.5$, $\theta_1=2$, and $\theta_2=5$

We then generate a vector of $y$-values according to the model and put the predictors together in a "feature matrix" `x_mat`
"""

np.random.seed(1234)  ## This ensures we get the same data if all of the other parameters remain fixed

num_obs = 100

x1 = np.random.uniform(0,10,num_obs)
x2 = np.random.uniform(0,10,num_obs)

eps = np.random.normal(0,.5,num_obs)

b = 1.5
theta_1 = 2
theta_2 = 5

y = b + theta_1*x1 + theta_2*x2 + eps

x_mat = np.array([x1,x2]).T

x_mat.shape

"""## Solving by Gradient Descent


For most numerical problems, we don't / can't know the underlying analytical solution. This is because we only arrive at analytical solutions by solving the equations mathematically, with pen and paper. That is more often than not just impossible. Fortunately, we have a way of converging to an approximate solution, by using **Gradient Descent**.


We will explore this very useful method because Neural Networks, along with many other complicated algorithms, are trained using Gradient Descent.  Seeing how gradient descent works on a simple example will build intuition and help us understand some of the nuances around setting the learning rate and other parameters.

## Exercise

The next several cells have code to perform (full-batch) gradient descent. **We have omitted some parameters for you to fill in**.
"""

## Parameters to play with
learning_rate = 1e-3
num_iter      = 10000
theta_initial = np.array([3,3])

def gradient_descent(learning_rate, num_iter, theta_initial):

    ## Initialization steps
    theta = theta_initial

    loss_vec = np.zeros(num_iter)

    ## Main Gradient Descent loop (for a fixed number of iterations)
    for i in range(num_iter):
        y_pred = np.dot(theta.T,x_mat.T)
        loss_vec[i] =  # CALCULE O ERRO...#
        grad_vec = (y-y_pred).dot(x_mat)/num_obs  #sum up the gradients across all observations and divide by num_obs
        grad_vec = grad_vec
        theta = theta + learning_rate*grad_vec
    return loss_vec

def plot_loss(loss_vec):
    plt.plot(loss_vec)
    plt.ylabel('Loss')
    plt.xlabel('num_iter')

loss_vec = gradient_descent(learning_rate, num_iter, theta_initial)
plot_loss(loss_vec)