# -*- coding: utf-8 -*-
"""Scikit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FMNPwY0yRvjyy4pA0PWbxwRI818sABmI

# Supervised Learning and K Nearest Neighbors Exercises

## Introduction

We will be using customer churn data from the telecom industry. We will load this data and use K-nearest neighbors to predict customer churn based on account characteristics. The data we will use are in a file called `Orange_Telecom_Churn_Data_OK.csv` found in the [GitHub repository](https://github.com/rosalvoneto/InteligenciaComputacional).

## Question 1

* Begin by importing the data. Examine the columns and data.
"""

# Import the data

"""## Question 2

* Notice that the data contains a phone number. Do you think this is good feature to use when building a machine learning model? Why or why not?

We will not be using it, so it can be dropped from the data.
"""

# Remove phone_number column



"""## Question 3

* Separate the feature columns (everything except `churned`) from the label (`churned`). This will create two tables.
* Fit a K-nearest neighbors model with a value of `k=3` to this data and predict the outcome on the same data.
"""

# Split the data into two dataframes

# Fit a K-nearest neighbors model with a value of k=3

"""## Question 4

Ways to measure error haven't been discussed in class yet, but accuracy is an easy one to understand--it is simply the percent of labels that were correctly predicted (either true or false).

* Write a function to calculate accuracy using the actual and predicted labels.
* Using the function, calculate the accuracy of this K-nearest neighbors model on the data.
"""

# Function to calculate accuracy

# Using the function

"""## Question 5

* Fit a K-nearest neighbors model using values of `k` (`n_neighbors`) ranging from 1 to 20.  Store the accuracy and the value of `k` used from each of these fits in a list or dictionary.
* Plot (or view the table of) the `accuracy` vs `k`. What do you notice happens when `k=1`? Why do you think this is? *Hint:* it's for the same reason discussed above.
"""

# K-nearest neighbors model

# Plot
import matplotlib.pyplot as plt