# -*- coding: utf-8 -*-
"""Cópia de Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zF6GaAq3Fshf_gYi1PtX8mJ4Fp_nG7G

# Pré-processamento e Transformação

## Introdução

Vamos pré-processar, transformar e salvar os dados para a etapa de modelagem.  Os dados que usaremos estão em um arquivo chamado  `Orange_Telecom_Churn_Data.csv` disponível no  [GitHub repository](https://github.com/rosalvoneto/InteligenciaComputacional).

## Questão 1

* Importe os dados;
* Examine as colunas.
"""

# Importar os dados
import pandas as pd

data = pd.read_csv('https://github.com/rosalvoneto/InteligenciaComputacional/raw/refs/heads/main/Orange_Telecom_Churn_Data.csv')

data.head(1).T

"""## Questão 2

* Elimine as variáveis irrelevantes: 'phone_number', 'area_code', 'state'.
"""

# Remove phone_number column
data.drop(['phone_number', 'area_code', 'state'], axis = 1, inplace=True)
data.head(1).T

data = pd.get_dummies(data, drop_first=True)
data.head(1).T



"""## Questão 3

* Separate os dados em dois: X_data (variáveis de entrada) e y_data (variável alvo `churned`);

* Dividir os dados em treinamento e teste usando train_test_split do sklearn.model_selection: X_train, X_test, y_train, y_test
"""

X_data = data.iloc[:,:-1]
X_data.head(1).T

y_data = data.iloc[:,-1]
y_data.head(1).T

"""## Questão 4

* Crie variáveis Dummies (Use a função get_dummies do pandas dataframe);
* Converta a variável alvo em numérica.
"""

# Separate os dados: X_data e  y_data


# Dividir os dados em treinamento e teste
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_data,
    y_data,
    test_size=0.3,
    random_state=42
)

# Dummies
from sklearn.preprocessing import MinMaxScaler

# 1. Instancia o escalador
scaler = MinMaxScaler()

# 2. Ajusta e transforma os dados de TREINO
X_train_scaled = scaler.fit_transform(X_train)

# 3. Transforma os dados de TESTE (usando apenas transform para evitar vazamento de dados)
X_test_scaled = scaler.transform(X_test)

y_train_scaled = scaler.fit_transform(y_train)

# 3. Transforma os dados de TESTE (usando apenas transform para evitar vazamento de dados)
y_test_scaled = scaler.transform(y_test)

y_test_scaled.head(1).T

"""## Questão 5

* Normalize X_train -> X_train_norm e X_test -> X_test_norm: use MinMaxScaler do sklearn.preprocessing;OBS: MinMaxScaler retorna um numpy.ndarray e não um DataFrame do pandas;
* Atualize X_train e X_test com os dados normalizados.
"""

# Normalizar

# Atualizar X_train com os dados normalizado

# Atualizar/Criar X_train com os dados normalizado

"""## Questão 6

* Examine os Dataframes;
* Salve os quatro arquivos.

"""

# Examinando X_train

# Examinando X_test

# Salvando os dados em arquivos