# -*- coding: utf-8 -*-
"""Cópia de Cópia de 04_Keras_First_NN_Excercises_1_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19C8ur5HRxHaQpBVnOLcMNPcl1NZqud5m

## Using Keras to Build and Train Neural Networks

In this exercise we will use a neural network to predict diabetes using the Pima Diabetes Dataset.  We will use the Keras package to quickly build and train a neural network.
## UCI Pima Diabetes Dataset

* UCI ML Repositiory (https://www.kaggle.com/uciml/pima-indians-diabetes-database)


### Attributes: (all numeric-valued)
   1. Number of times pregnant
   2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
   3. Diastolic blood pressure (mm Hg)
   4. Triceps skin fold thickness (mm)
   5. 2-Hour serum insulin (mu U/ml)
   6. Body mass index (weight in kg/(height in m)^2)
   7. Diabetes pedigree function
   8. Age (years)
   9. Class variable (0 or 1)

The UCI Pima Diabetes Dataset which has 8 numerical predictors and a binary outcome.
"""

# Commented out IPython magic to ensure Python compatibility.
#Preliminaries

from __future__ import absolute_import, division, print_function  # Python 2/3 compatibility

import warnings
warnings.filterwarnings("ignore")


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, precision_recall_curve, roc_auc_score, roc_curve, accuracy_score
from sklearn.ensemble import RandomForestClassifier

from sklearn.neighbors import KNeighborsClassifier

import seaborn as sns

# %matplotlib inline

## Import Keras objects for Deep Learning

from keras.models  import Sequential
from keras.layers import Input, Dense, Flatten, Dropout, BatchNormalization, Activation
from keras.optimizers import Adam, SGD, RMSprop

## Load in the data set (Internet Access needed)

url = "https://github.com/rosalvoneto/InteligenciaComputacional/raw/refs/heads/main/Orange_Telecom_Churn_Data_OK.csv"

diabetes_df = pd.read_csv(url)

diabetes_df.drop('phone_number', axis = 1, inplace=True)

# Imprimir o numero de linhas e colunas de diabetes_df

diabetes_df.shape

# Visualizar as 5 primeiras linhas do diabetes_df

diabetes_df.head()

# Coloque o conteudo da coluna has_diabetes de diabetes_df na variável y e todas as outras colunas em X. Dica: Use o comando iloc

X = diabetes_df.iloc[:, :-1]  # Pega todas as colunas, exceto a última
y = diabetes_df.iloc[:, -1]

# Split the data to Train, and Test (75%, 25%)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=11111)

## Normalize os dados usando StandardScaler() já importado. Use as variáveis X_train_norm e X_test_norm para os dados de treinamento e teste respectivamente

scaler = StandardScaler()

# Ajusta o scaler nos dados de treino e os transforma
X_train_norm = scaler.fit_transform(X_train)

# Transforma os dados de teste usando o scaler já ajustado aos de treino
X_test_norm = scaler.transform(X_test)

"""## Build a Single Hidden Layer Neural Network

We will use the Sequential model to quickly build a neural network.  Our first network will be a single layer network.  We have 8 variables, so we set the input shape to 8.  Let's start by having a single hidden layer with 12 nodes.
"""

# Define the Model
# Input size is 8-dimensional
# 1 hidden layer, 12 hidden nodes, sigmoid activation
# Final layer has just one node with a sigmoid activation (standard for binary classification)

# O nome do modelo deve ser model_1

model_1 = Sequential(
    [
        # Camada oculta: 12 nós, ativação sigmoid e entrada de dimensão 8
        Dense(12, activation="sigmoid", input_shape=(17,)),
        # Camada de saída: 1 nó, ativação sigmoid para classificação binária
        Dense(1, activation="sigmoid"),
    ]
)

#  This is a nice tool to view the model you have created and count the parameters

model_1.summary()

"""### Comprehension question:
Why do we have 121 parameters?  Does that make sense?


Let's fit our model for 200 epochs.
"""

# Fit(Train) the Model

# Compile the model with Optimizer, Loss Function and Metrics

model_1.compile(
    SGD(learning_rate=0.003), "binary_crossentropy", metrics=["accuracy"]
)

# Treinamento
run_hist_1 = model_1.fit(
    X_train_norm, y_train, validation_data=(X_test_norm, y_test), epochs=200
)
# the fit function returns the run history.
# It is very convenient, as it contains information about the model fit, iterations etc.

# Faça a predição do modelo nos dados de teste "X_test_norm"
# use a variável y_pred_prob_nn_1 para armazenar as probalidades (saída da função predict)
# use a variável y_pred_class_nn_1 para armazenar a resposta binária, ou seja, 1 se a probabilidade for maior do que .5 ou 0 caso contrário

# Faz a predição das probabilidades
y_pred_prob_nn_1 = model_1.predict(X_test_norm)

# Converte as probabilidades em classes binárias (1 se > 0.5, caso contrário 0)
y_pred_class_nn_1 = (y_pred_prob_nn_1 > 0.5).astype(int)

# Let's check out the outputs to get a feel for how keras apis work.
y_pred_class_nn_1[:10]

y_pred_prob_nn_1[:10]

# Print model performance
print('accuracy is {:.3f}'.format(accuracy_score(y_test,y_pred_class_nn_1)))

"""Let's look at the `run_hist_1` object that was created, specifically its `history` attribute."""

run_hist_1.history.keys()

"""Let's plot the training loss and the validation loss over the different epochs and see how it looks."""

fig, ax = plt.subplots()
ax.plot(run_hist_1.history["loss"],'r', marker='.', label="Train Loss")
ax.plot(run_hist_1.history["val_loss"],'b', marker='.', label="Validation Loss")
ax.legend()

"""Looks like the losses are still going down on both the training set and the validation set.  This suggests that the model might benefit from further training.  Let's train the model a little more and see what happens. Note that it will pick up from where it left off. Train for 1000 more epochs."""

## Note that when we call "fit" again, it picks up where it left off
run_hist_1b = model_1.fit(X_train_norm, y_train, validation_data=(X_test_norm, y_test), epochs=1000)

n = len(run_hist_1.history["loss"])
m = len(run_hist_1b.history['loss'])
fig, ax = plt.subplots(figsize=(16, 8))

ax.plot(range(n), run_hist_1.history["loss"],'r', marker='.', label="Train Loss - Run 1")
ax.plot(range(n, n+m), run_hist_1b.history["loss"], 'hotpink', marker='.', label="Train Loss - Run 2")

ax.plot(range(n), run_hist_1.history["val_loss"],'b', marker='.', label="Validation Loss - Run 1")
ax.plot(range(n, n+m), run_hist_1b.history["val_loss"], 'LightSkyBlue', marker='.',  label="Validation Loss - Run 2")

ax.legend()

"""Note that this graph begins where the other left off.  While the training loss is still going down, it looks like the validation loss has stabilized (or even gotten worse!).  This suggests that our network will not benefit from further training.  What is the appropriate number of epochs?"""