# -*- coding: utf-8 -*-
"""Exercicio_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLJ7NEJZR2LiFzpIM1B4zO61kg6jBNcU

# Disciplina: Inteligência Artificial
## Exercício 02

### Aula: Python

Prof. Rosalvo Neto

## Questão 01)
Desenvolva uma função com o nome **num_par** que recebe uma lista de números como parâmetros e retorna uma lista com números que são pares.
"""

# Escreva seu código aqui!
from exercicio_01 import Number

"""***Execute o código abaixo para testar sua função!***"""

numeros = [1, 2, 3, 4, 5]


def to_number(num: int | float | Number) -> Number:
    return Number(num)


def is_even(num: Number) -> bool:
    return num.modulo(2) == 0


even_numbers_filtered_and_mapped = list(filter(is_even, map(to_number, numeros)))

print(even_numbers_filtered_and_mapped)

even_numbers = [num for num in (Number(num) for num in numeros) if num % 2 == 0]

print(even_numbers)

"""***Resultado esperado:***
[2, 4]
"""