# -*- coding: utf-8 -*-
"""Exercicio_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gafxs7laR1kB_sUV0dxlm7i6t-EMozf

# Disciplina: Inteligência Artificial
## Exercício 03

### Aula: Python

Prof. Rosalvo Neto

**Questão 01)** Ler o conteúdo do arquivo palavras e gerar um dicionário com a quantidade de palavras onde a chave é a palavra e o valor é a quantidade de ocorrências da palavra no arquivo. Crie uma função chamada **getPalavrasCount**. Essa função recebe como parâmetro o nome do arquivo "palavras.txt" e retorna um dicionário.**Dica:** use a função get do dicionário. Ver: https://www.tutorialspoint.com/python/dictionary_get.htm
"""

# Escreva seu código aqui!

"""#### Execute o código abaixo para testar sua função!"""

getPalavrasCount("palavras.txt")

"""### Resultado esperado:
{'Flamengo': 3,
 'Palmeiras': 2,
 'Corinthians': 4,
 'Cruzeiro': 3,
 'Fluminense': 2,
 'São': 3,
 'Paulo': 3,
 'Santos': 1,
 'Atlético': 1,
 'Paranaense': 1,
 'Vasco': 1,
 'da': 1,
 'Gama': 1}
"""