# -*- coding: utf-8 -*-
"""Exercicio_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLJ7NEJZR2LiFzpIM1B4zO61kg6jBNcU

# Disciplina: Inteligência Artificial
## Exercício 02

### Aula: Python

Prof. Rosalvo Neto
"""
from exercicio_01 import Number

"""## Questão 04)
Desenvolva uma função com o nome **ordena** que recebe uma lista de números como parâmetro e retorna uma lista ordenada. Você deve usar o laço de repetição **while** e a função min() que já está disponível. A função min() recebe como parâmetro uma lista e retorna o menor valor desta lista. Dica: use as funções append() and remove() da lista.
"""


def bubble_sort(numbers: list[Number]) -> list[Number]:

    if not numbers:
        return []

    sorted_list = list(numbers)
    size = len(sorted_list)

    for i in range(size - 1):
        swapped = False
        for j in range(size - 1 - i):
            if sorted_list[j] > sorted_list[j + 1]:
                sorted_list[j], sorted_list[j + 1] = sorted_list[j + 1], sorted_list[j]
                swapped = True

        if not swapped:
            break

    return sorted_list


def selection_sort(numbers: list[Number]) -> list[Number]:
    """Selection Sort (Ordenação por Seleção)
    Procura o menor elemento da lista não ordenada e o coloca na primeira posição livre."""
    sorted_list = list(numbers)
    n = len(sorted_list)

    for i in range(n):
        min_index = i
        for j in range(i + 1, n):
            if sorted_list[j] < sorted_list[min_index]:
                min_index = j

        sorted_list[i], sorted_list[min_index] = sorted_list[min_index], sorted_list[i]

    return sorted_list


def insertion_sort(numbers: list[Number]) -> list[Number]:
    """Insertion Sort (Ordenação por Inserção)
    Funciona exatamente como organizar cartas de um baralho na mão: pega um elemento e
    o insere na posição correta em relação aos elementos anteriores."""
    sorted_list = list(numbers)

    for i in range(1, len(sorted_list)):
        key = sorted_list[i]
        j = i - 1
        while j >= 0 and sorted_list[j] > key:
            sorted_list[j + 1] = sorted_list[j]
            j -= 1
        sorted_list[j + 1] = key

    return sorted_list

def quick_sort(numbers: list[Number]) -> list[Number]:
    """Ordena uma lista de Number usando Quick Sort (versão funcional/recursiva)."""
    # Caso base da recursão: listas com 0 ou 1 elemento já estão ordenadas
    if len(numbers) <= 1:
        return list(numbers)

    # Escolhemos o elemento do meio como pivô
    pivot = numbers[len(numbers) // 2]

    # Particionamos os elementos em relação ao pivô
    left = [x for x in numbers if x < pivot]
    middle = [x for x in numbers if x == pivot]
    right = [x for x in numbers if x > pivot]

    # Chamada recursiva para a esquerda e direita, unindo os resultados
    return quick_sort(left) + middle + quick_sort(right)


"""***Execute o código abaixo para testar sua função!***"""

L = [Number(num) for num in (3, 2, 5, 1, 4)]
print(quick_sort(L))

"""***Resultado esperado:***
[1, 2, 3, 4, 5]
"""
