# -*- coding: utf-8 -*-
"""Exercicio_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLJ7NEJZR2LiFzpIM1B4zO61kg6jBNcU

# Disciplina: Inteligência Artificial
## Exercício 02

### Aula: Python

Prof. Rosalvo Neto

## Questão 01)
Desenvolva uma função com o nome **num_par** que recebe uma lista de números como parâmetros e retorna uma lista com números que são pares.
"""

# Escreva seu código aqui!
from exercicio_01 import Number
"""
## Questão 02)
Desenvolva uma função com o nome **media** que recebe uma lista de números como parâmetros e retorna a média.
"""

# Escreva seu código aqui!


def verify_empty_list(numbers):
    if not numbers:
        raise ValueError('A lista não pode estar vazia.')


def mean(numbers: list[Number]) -> Number:

    verify_empty_list(numbers)

    numbers_sum = sum(numbers, start=Number(0))
    return numbers_sum / len(numbers)


def median(numbers: list[Number]) -> Number:

    verify_empty_list(numbers)

    sorted_nums = sorted(numbers)

    index_middle = len(sorted_nums) // 2

    median = sorted_nums[index_middle]

    if len(sorted_nums) % 2 == 0:
        # usa o operador bitwise para acessar o índice simétrico (index_middle - 1)
        median += sorted_nums[~index_middle]
        median /= 2

    return median


def mode(numbers: list[Number]) -> list[Number]:

    verify_empty_list(numbers)

    frequencies: dict[Number, int] = {}

    for num in numbers:
        frequencies[num] = frequencies.get(num, 0) + 1

    max_occurrences = max(frequencies.values())

    return [key for key, count in frequencies.items() if count == max_occurrences]


"""***Execute o código abaixo para testar sua função!***"""

L = [Number(num) for num in (1, 2, 3, 4, 5)]
print(mean(L))

"""***Resultado esperado:***
3.0

"""
