# -*- coding: utf-8 -*-
"""Exercicio_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLJ7NEJZR2LiFzpIM1B4zO61kg6jBNcU

# Disciplina: Inteligência Artificial
## Exercício 02

### Aula: Python

Prof. Rosalvo Neto

## Questão 01)
Desenvolva uma função com o nome **num_par** que recebe uma lista de números como parâmetros e retorna uma lista com números que são pares.
"""

# Escreva seu código aqui!

"""***Execute o código abaixo para testar sua função!***"""

L = [1, 2, 3, 4 , 5]
num_par(L)

"""***Resultado esperado:***
[2, 4]

## Questão 02)
Desenvolva uma função com o nome **media** que recebe uma lista de números como parâmetros e retorna a média.
"""

# Escreva seu código aqui!

"""***Execute o código abaixo para testar sua função!***"""

L = [1, 2, 3, 4 , 5]
media(L)

"""***Resultado esperado:***
3.0

## Questão 03)
Desenvolva uma função com o nome **intersecao** que recebe duas listas como parâmetros e retorna uma lista com os elemetos comuns entre as duas listas.
"""

# Escreva seu código aqui!

"""***Execute o código abaixo para testar sua função!***"""

L1 = ['a', 'd', 'f', 'g']
L2 = ['a', 'b', 'c', 'd']
intersecao(L1, L2)

"""***Resultado esperado:***
['a', 'd']

## Questão 04)
Desenvolva uma função com o nome **ordena** que recebe uma lista de números como parâmetro e retorna uma lista ordenada. Você deve usar o laço de repetição **while** e a função min() que já está disponível. A função min() recebe como parâmetro uma lista e retorna o menor valor desta lista. Dica: use as funções append() and remove() da lista.
"""

# Escreva seu código aqui!

"""***Execute o código abaixo para testar sua função!***"""

L = [3, 2, 5, 1, 4]
ordena(L)

"""***Resultado esperado:***
[1, 2, 3, 4, 5]
"""