# -*- coding: utf-8 -*-
"""Exercicio_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xe4aQyFGgfv8LRspsO2SEmgGtVKgBPtX

# Disciplina: Inteligência Artificial
## Exercício 04

### Aula: Python

Prof. Rosalvo Neto

**Questão 01)** Criar uma função que irá calcular o Erro Quadrático Médio, do inglês Mean squared error (MSE). A função deve se chamar ***MSE*** e recebe como parâmtro dois array (X, Y) e retorna
o valor do MSE = $\displaystyle\frac{1}{n}\sum_{t=1}^{n}(x_{i} -y_{i})^2$

Ver: https://pt.wikipedia.org/wiki/Erro_quadr%C3%A1tico_m%C3%A9dio
"""

# Escreva seu código aqui!

"""#### Execute o código abaixo para testar sua função!"""

X = np.array([1, 2, 3, 4])
Y = np.array([2, 5, 6, 7])
MSE(X, Y)

"""### Resultado esperado:
7.0
"""