# -*- coding: utf-8 -*-
"""Exercicio_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLJ7NEJZR2LiFzpIM1B4zO61kg6jBNcU

# Disciplina: Inteligência Artificial
## Exercício 02

### Aula: Python

Prof. Rosalvo Neto
"""
from exercicio_01 import Number
"""

## Questão 03)
Desenvolva uma função com o nome **intersecao** que recebe duas listas como parâmetros e retorna uma lista com os elemetos comuns entre as duas listas.
"""


def interserction(a: set[Number], b: set[Number]) -> set[Number]:
    if not a or not b:
        return set()

    return {num for num in a if num in b}


def intersection_builtin(a: set[Number], b: set[Number]) -> set[Number]:
    """O python consegue fazer a intersecção de conjuntos nativamente com o operador &
    em classes que implementam __hash__ e __eq__"""
    return a & b


def union(a: set[Number], b: set[Number]) -> set[Number]:
    result = set(a)
    result.update(b)
    return result


def union_builtin(a: set[Number], b: set[Number]) -> set[Number]:
    """O python consegue fazer a união de conjuntos nativamente com o operador |
    em classes que implementam __hash__ e __eq__"""
    return a | b


def difference(a: set[Number], b: set[Number]) -> set[Number]:
    return {num for num in a if num not in b}


def difference_builtin(a: set[Number], b: set[Number]) -> set[Number]:
    """O python consegue fazer a diferença de conjuntos nativamente com o operador -
    em classes que implementam __hash__ e __eq__"""
    return a - b


def symmetric_difference(a: set[Number], b: set[Number]) -> set[Number]:
    result: set[Number] = {num for num in a if num not in b}
    result.update({num for num in b if num not in a})
    return result


def symmetric_difference_builtin(a: set[Number], b: set[Number]) -> set[Number]:
    """O python consegue fazer a diferença simétrica de conjuntos nativamente com
    o operador ^ em classes que implementam __hash__ e __eq__"""
    return a ^ b


"""***Execute o código abaixo para testar sua função!***"""

L1 = {Number(num) for num in (1, 2, 3, 4, 5)}
L2 = {Number(num) for num in (2, 8, 14, 3)}
print(interserction(L1, L2))

"""***Resultado esperado:***
{Number(2),Number(3)}

"""